### ISSUE TITLE
Align Discuss

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery-nsm#115]
**Description**
Align the Discuss with the others

**Current Behavior**
<img width="1440" alt="Screenshot 2021-07-08 at 7 17 08 PM" src="https://user-images.githubusercontent.com/53532328/124933230-5a645700-e021-11eb-934a-7b55d50b5720.png">

**Expected Behavior**
<img width="1440" alt="Screenshot 2021-07-08 at 7 17 30 PM" src="https://user-images.githubusercontent.com/53532328/124933287-66501900-e021-11eb-911f-ba88d602aa5d.png">

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by The-Loony-Coder** [comment]
hey @warunicorn19 ,can I have this issue.

**Comment by warunicorn19** [comment]
sure @The-Loony-Coder

**Comment by The-Loony-Coder** [comment]
![meshrynsm](https://user-images.githubusercontent.com/55737921/125400229-47f66e80-e3cf-11eb-958f-0b4dc53e0c3f.png)
Hey @warunicorn19 
can check it  again , I think its already aligned

**Comment by warunicorn19** [comment]
<img width="1440" alt="Screenshot 2021-07-13 at 11 50 49 AM" src="https://user-images.githubusercontent.com/53532328/125401379-b2f47500-e3d0-11eb-83d5-9cea20d1c09c.png">

still looks unaligned on my system

**Comment by The-Loony-Coder** [comment]
hey @warunicorn19 .I 've made the updates.Please have a look.
