### ISSUE TITLE
Add adapter version at build time

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-nsm#128]
See: https://github.com/meshery/meshery-nginx-sm/issues/43

**Comment by sayantan1413** [comment]
@DelusionalOptimist I think this adapter already incorporate adapter version at buildtime . https://github.com/meshery/meshery-nsm/blob/master/Dockerfile#L3-L4

**Comment by DelusionalOptimist** [comment]
Okay. Thanks @sayantan1413 :+1:
