### ISSUE TITLE
Update go version in github actions workflows to 1.17

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery-nsm#147]
#### Current Behavior
Many of places in the workflows still mention go version 1.16 yet the adapters use go version 1.17

#### Desired Behavior
Workflows should also use go version 1.17

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by haanhvu** [comment]
@Zanda256 I would like to work on this. Could you assign to me please^^

**Comment by 8rxn** [comment]
Hey @leecalcote, I would like to work on this issue.

**Comment by VaibhavMalik4187** [comment]
@leecalcote Can you please assign this to me? Thanks

**Comment by leecalcote** [comment]
@VaibhavMalik4187 yes, although, we're using 1.20 now. Please use this version.

**Comment by VaibhavMalik4187** [comment]
@leecalcote The go version used in the workflows is defined as a secret variable. And I do not have access to those secrets. What should we do in this case?

**Comment by leecalcote** [comment]
I'm tagging @nebula-aac, who can offer counsel in terms of our new norm (or not) to explicitly define these versions in workflows and not in secrets any longer.

**Comment by VaibhavMalik4187** [comment]
> I'm tagging @nebula-aac, who can offer counsel in terms of our new norm (or not) to explicitly define these versions in workflows and not in secrets any longer.

@nebula-aac would you like to offer your assistance in this case?

**Comment by leecalcote** [comment]
@VaibhavMalik4187 not hearing from @nebula-aac, let's proceed with displacement of the secret with an explicit version number listed. Let's jump to 1.20

**Comment by VaibhavMalik4187** [comment]
> @VaibhavMalik4187 not hearing from @nebula-aac, let's proceed with displacement of the secret with an explicit version number listed. Let's jump to 1.20

On it.
