### ISSUE TITLE
[CI] Update Multi Platform build and Release workflow

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-nsm#152]
#### Current Behavior

Currently, the [multiplatform.yml](https://github.com/meshery/meshery-nsm/blob/master/.github/workflows/multi-platform.yaml) file is sending unwanted build arguments to docker build process because of which release tag and commit_sha are not being passed over to the image and hence the version of meshery adapter are not visible on-hovering adapters chips on Meshery UI Dashboard.

#### Desired Behavior

This would be fixed when correct build args are passed to the docker build step inside multiplatform workfow.
Required Args:
- VERSION
- GIT_COMMITSHA

Check this commit for reference:
https://github.com/meshery/meshery-consul/commit/446ad170c938c9bfe22e6e8710459d63395b9148

related to: https://github.com/meshery/meshery/issues/6245

---

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by legendarykamal** [comment]
hi @theBeginner86 a devops related issue, can I pick this up :)
