### ISSUE TITLE
Issue Template Updates for Figma link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nsm#161]
#### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

#### Desired Behavior
Each template that has a reference to Figma in its resources section should an invite link added.

#### Implementation

In each [issue template](../blob/master/.github/ISSUE_TEMPLATE/) that refers to Figma, replace the current line referring to Figma with this line:

```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

#### Acceptance Tests
1. All references to Figma include the "open invite" link.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by yashchaddha** [comment]
Hi @leecalcote I would like to contribute on this. Can i please get assigned to this?

**Comment by Ghat0tkach** [comment]
**This issue is for the first-timers only**.Let's get some fresh and new contributors . Here is your chance newcomers 😉

**Comment by aryanas159** [comment]
Hey! Can I be assigned to this?

**Comment by leecalcote** [comment]
@aryanas159, sounds like we're holding out for a first-timer...

**Comment by aryanas159** [comment]
@leecalcote  Oh,  ok no problem.

**Comment by H-a-rshit** [comment]
Hi @leecalcote I would like to contribute on this. Can i please get assigned to this?

**Comment by Ghat0tkach** [comment]
> Hi @leecalcote I would like to contribute on this. Can i please get assigned to this?

Hello Harshit , you can start working on the issue , Remember only draft PR when you get assigned.

**Comment by H-a-rshit** [comment]
So basically what I need to do is 
1.Go to this link [https://github.com/meshery/meshery-nsm/tree/master/.github/ISSUE_TEMPLATE]
2. And need to Make changes in [bug_report.md](https://github.com/meshery/meshery-nsm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) , [documentation.md](https://github.com/meshery/meshery-nsm/blob/master/.github/ISSUE_TEMPLATE/documentation.md) , [feature_request.md](https://github.com/meshery/meshery-nsm/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) , [question.md](https://github.com/meshery/meshery-nsm/blob/master/.github/ISSUE_TEMPLATE/question.md).
3. I have to replace the link for figma design file in bug_report.md and for figma in feature_request.md 

Please correct me if I am wrong

**Comment by H-a-rshit** [comment]
I have made changes in feature_request.md 
I have created a pull request, [PULL REQUEST ](https://github.com/meshery/meshery-nsm/pull/162)

**Comment by H-a-rshit** [comment]
Hi @leecalcote please check the pull request.

**Comment by leecalcote** [comment]
Oh, great, @H-a-rshit.

@yashchaddha, would you like to offer review?

**Comment by thisiskaransgit** [comment]
Closing as completed via #162
