### ISSUE TITLE
NSM Provisioning Fails - missing /charts manifests

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-nsm#52]
**Description**
Using the latest version of NSM adapter, provisioning of NSM fails. See the error below. Helm charts have moved directories.

**Expected Behavior**
Short-term, the provisioning of NSM can be updated to use the new path to the charts directory - https://github.com/networkservicemesh/networkservicemesh/tree/master/deployments/helm

Long-term, the NSM adapter needs to be updated to use `helm`; to deploy NSM in the fashion in which the NSM project defines (using `networkservicemesh/helm-charts`). See #53 .

**Logs**

```
ERRO[0045] render manifests error: found in requirements.yaml, but missing in charts/ directory: config
DEBU[0045] sending event: &meshes.EventsResponse{EventType:2, Summary:"Error while deploying NSM", Details:"render manifests error: found in requirements.yaml, but missing in charts/ directory: config", OperationId:"ca151287-f9f6-4e12-afba-0a134fedd94c", XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
```

**Comment by leecalcote** [comment]
@ivanayov, here's a relatively simple bug to fix. This issue is currently causing the NSM adapter not to function as users are not able to deploy NSM using Meshery because of it.

**Comment by iambami** [comment]
I think this issue is fixed. I will be closing it now.
